setwd("E:/2D/Final/Prob_Stat/simpleAnalysis01/probStat_simpleAnalysis")
dat<-read.csv("water_potability.csv",header=T)
dataRm_Na <- na.omit(dat)
data_Turbidity_RM <- subset(dataRm_Na,Turbidity<=5)
data_pH_RM <- subset(dataRm_Na,between(ph,6.5,8.5))
data_Solids_RM <- subset(dataRm_Na,between(Solids,500,1000))
data_Chloramines_RM <- subset(dataRm_Na,Chloramines<=4)
data_Sulfate_RM <- subset(dataRm_Na,between(Sulfate,3,30))
data_Conductivity_RM <- subset(dataRm_Na,Conductivity<=400)
data_Organic_carbon_RM <- subset(dataRm_Na,Organic_carbon<=25)
data_Trihalomethanes_RM <- subset(dataRm_Na,Trihalomethanes<=80)
